# Generated by Django 4.2.13 on 2024-06-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table='new_user',
        ),
    ]
