# Generated by Django 4.2.13 on 2024-06-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_managers_remove_newuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table='user',
        ),
    ]
