# Generated by Django 4.2.13 on 2024-06-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_managers_remove_newuser_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
