# Generated by Django 4.2.13 on 2024-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='brand',
            field=models.ManyToManyField(related_name='subcategories', to='goods.brand'),
        ),
        migrations.AddField(
            model_name='type',
            name='brand',
            field=models.ManyToManyField(related_name='types', to='goods.brand'),
        ),
    ]
