# Generated by Django 4.2.13 on 2024-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_subcategory_brand_type_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='brand',
            field=models.ManyToManyField(related_name='subcategor', to='goods.brand'),
        ),
    ]
