# Generated by Django 4.2.13 on 2024-06-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_goods_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='user',
        ),
    ]
