# Generated by Django 5.0.6 on 2024-06-19 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=9, verbose_name='phone number')),
                ('delivery', models.CharField(choices=[('Courier', 'Delivery by courier at a time convenient for you'), ('Pickup', 'Pickup, Minsk, Nemanskaya 20'), ('Post', 'Delivery by post to the address you provide')], max_length=10, verbose_name='delivery method')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='delivery address')),
                ('delivery_date', models.DateField()),
                ('payment', models.CharField(choices=[('Cash', 'By cash'), ('Card', 'By card'), ('Online', 'Online payment')], max_length=40, verbose_name='payment method')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('status', models.CharField(default='in processing', max_length=50, verbose_name='order status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.product', verbose_name='product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sold item',
                'verbose_name_plural': 'sold items',
            },
        ),
    ]
